# Generated by Django 6.0 on 2026-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
